alias duall='du -sch .[!.]* * |sort -h'
alias xo='xdg-open'
alias m='make'
alias mw='make watch'
alias mo='make && xo master.pdf'
alias pullloop='while true; do git pull; done'
alias ssh-pass='ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no'
alias scp-pass='scp -o PreferredAuthentications=password -o PubkeyAuthentication=no'


# list recursive using tree
function lr() {
    tree -L ${1:-2}
}

# aau projects
alias aau-p3r='cd ~/Documents/university/p3/p3gr350rapport'
alias aau-p3s='cd ~/Documents/university/p3/p3gr350software'
alias aau-p4r='cd ~/Documents/university/p4/save-brazil-report'
alias aau-p4s='cd ~/Documents/university/p4/save-brazil'
alias aau-p5r='cd ~/Documents/university/p5/sniffer-report'
alias aau-p5s='cd ~/go/src/sniffer'
alias aau-work='cd ~/Documents/university/studentambassador'
alias aau-sdg='cd ~/Documents/projects/sdg'
alias aau-note='cd ~/Documents/university/itc17-shared/'
alias aau-p7r='cd ~/Documents/university/p7/p7-report'

# projects
alias project='cd  ~/Documents/projects'
alias docker-images='cd ~/Documents/projects/docker-images'
alias dotf='cd ~/Documents/projects/dot-files/dotfiles'


function f() {
    local file
    file=$(fzf +m --height 40% --reverse) && atom "$file"
}

function fo() {
    local file
    file=$(fzf +m --height 40% --reverse) && xo "$file"
}

function p() {
    local dir
    dir=$(find ${1:-.} -type d 2> /dev/null | fzf +m) && cd "$dir"
}
